export const ActionTypes = {
    RENAME_CHAPTER: "RENAME_CHAPTER",
    RENAME_LESSON: "RENAME_LESSON",
    ADD_CHAPTER: "ADD_CHAPTER",
    ADD_LESSON: "ADD_LESSON",
    CREATE_QUIZ_SUCCESS: "CREATE_QUIZ_SUCCESS"
}