export {default as AddCourse} from './AddCourse'; 
export {default as AllCourses }from './AllCourses'; 
export {default as Profile} from './Profile'; 
export {default as Status} from './Status'; 
export {default as AddInstructor} from './AddInstructor';
export {default as InstructorsList} from './InstructorsList';
export {default as CreateCourse} from './CreateCourse';
export {default as EnrolledCourses} from './EnrolledCourses';
export {default as Activities} from './Activities';