export { default as Dashboard } from "./Dashboard";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Landing } from "./Landing";
export { default as CreateLessonForm } from "./CreateLessonForm";
export {default as SingleCourse} from "./SingleCourse"; 
export {default as Lessons} from './Lessons'; 
export {default as ErrorPage} from './ErrorPage';
export {default as MyQuestions} from './MyQuestions';
export {default as ForumLayout} from './ForumLayout';
export {default as HomeLayout} from './HomeLayout'; 